# Netlify Configuration for El Dorado Platform
# Purpose: Marketing site, docs, and staging environment

[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

# Redirect rules
[[redirects]]
  from = "/docs/*"
  to = "/documentation/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://api.el-dorado.onrender.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment variables (set in Netlify dashboard)
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY
# NEXT_PUBLIC_FIREBASE_API_KEY
# NEXT_PUBLIC_FIREBASE_PROJECT_ID
# NEXT_PUBLIC_RENDER_API_URL
